apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-name: "SciKit v1.10 - Elyra Notebook Image"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Scikit"
  name: elyra-scikit-customnotebook
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/ml-on-k8s/scikit-notebook:v1.2.0
    name: latest
status: 
  tags:
    - tag: latest
      dockerImageReference: quay.io/ml-on-k8s/scikit-notebook:v1.2.0