apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elyra-notebook-base-imagestream.yaml
  - elyra-notebook-spark3-imagestream.yaml
  - customnotebook-imagestream.yaml


commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "custom-images"
