apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: seldon
      app.kubernetes.io/instance: seldon1
      app.kubernetes.io/name: seldon
      app.kubernetes.io/version: v0.5
      control-plane: seldon-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: seldon
        app.kubernetes.io/instance: seldon1
        app.kubernetes.io/name: seldon
        app.kubernetes.io/version: v0.5
        control-plane: seldon-controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --webhook-port=8443
        - --create-resources=true
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          value: 'ml-workshop'
        - name: RELATED_IMAGE_EXECUTOR
          value: docker.io/seldonio/seldon-core-executor:1.12.0
        - name: RELATED_IMAGE_ENGINE
          value: docker.io/seldonio/seldon-engine:1.12.0
        - name: RELATED_IMAGE_STORAGE_INITIALIZER
          value: docker.io/seldonio/storage-initializer:1.12.0
        - name: RELATED_IMAGE_SKLEARNSERVER
          value: docker.io/seldonio/sklearnserver:1.12.0
        - name: RELATED_IMAGE_XGBOOSTSERVER
          value: docker.io/seldonio/xgboostserver:1.12.0
        - name: RELATED_IMAGE_MLFLOWSERVER
          value: docker.io/seldonio/mlflowserver:1.12.0
        - name: RELATED_IMAGE_TFPROXY
          value: docker.io/seldonio/tfproxy:1.12.0
        - name: RELATED_IMAGE_TENSORFLOW
          value: docker.io/seldonio/tensorflow-serving:1.12.0
        - name: MANAGER_CREATE_RESOURCES
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONTROLLER_ID
        - name: AMBASSADOR_ENABLED
          value: "true"
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "false"
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          value: docker.io/seldonio/engine:1.7.0
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: ENGINE_CONTAINER_USER
        - name: ENGINE_LOG_MESSAGES_EXTERNALLY
          value: "false"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_DEFAULT_ENV_SECRET_REF_NAME
        - name: PREDICTIVE_UNIT_METRICS_PORT_NAME
          value: metrics
        - name: ENGINE_SERVER_GRPC_PORT
          value: "5001"
        - name: ENGINE_SERVER_PORT
          value: "8000"
        - name: ENGINE_PROMETHEUS_PATH
          value: /prometheus
        - name: ISTIO_ENABLED
          value: "false"
        - name: KEDA_ENABLED
          value: "false"
        - name: ISTIO_GATEWAY
          value: istio-system/seldon-gateway
        - name: ISTIO_TLS_MODE
        - name: USE_EXECUTOR
          value: "true"
        - name: EXECUTOR_CONTAINER_IMAGE_AND_VERSION
          value: seldonio/seldon-core-executor:1.7.0
        - name: EXECUTOR_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EXECUTOR_PROMETHEUS_PATH
          value: /prometheus
        - name: EXECUTOR_SERVER_PORT
          value: "8000"
        - name: EXECUTOR_CONTAINER_USER
        - name: EXECUTOR_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: EXECUTOR_SERVER_METRICS_PORT_NAME
          value: metrics
        - name: EXECUTOR_REQUEST_LOGGER_DEFAULT_ENDPOINT
          value: http://default-broker
        - name: DEFAULT_USER_ID
        - name: EXECUTOR_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: EXECUTOR_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_LIMIT
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_LIMIT
          value: 512Mi
        # image: registry.connect.redhat.com/seldonio/seldon-core-operator@sha256:d50e4585f1f212b3fd5aa4200ccb2e2260b44cf17ed4d0fc89bfa61cf1969b9b
        image: docker.io/seldonio/seldon-core-operator:1.12.0
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 8443
          name: webhook-server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: seldon-manager
      serviceAccountName: seldon-manager
      terminationGracePeriodSeconds: 10


