apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: seldon-operator.v1.11.1-seldon-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-operator.v1.11.1-seldon-manager-role
subjects:
- kind: ServiceAccount
  name: seldon-manager
  namespace: ml-workshop


