apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seldon-operator.v1.11.1-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seldon-operator.v1.11.1-clusterrole
subjects:
- kind: ServiceAccount
  name: seldon-manager
  namespace: ml-workshop

  