version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${PWD}/data/nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: mlops-proxy
    restart: always
    networks:
      mlops_study_network:
networks:
  mlops_study_network:
    name: mlops_study_network
    external: true