kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata: 
  name: route.route.openshift.io
spec:
  group: route.openshift.io
  scope: Namespaced
  names:
    kind: Route
    plural: route
    singular: route  
  versions:
    - name: v1
      served: true
      storage: true      

      schema:
        openAPIV3Schema: 
          description: >-
            Defining the CRD so to use the as-is jhhub from ODH
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                to:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    weight:
                      type: integer
                port:
                  type: object
                  properties:
                    targetPort:
                      type: string
                tls:
                  type: object
                  properties:
                    termination:
                      type: string
                    insecureEdgeTerminationPolicy:
                      type: string
                wildcardPolicy:
                  type: string
