apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - subscription.yaml
  - prometheus.yaml
  - prometheus-role-bindings.yaml
  - prometheus-role.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "prometheus"




configMapGenerator:
- name: prometheusparameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: prometheusparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace