---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-prometheus-monitoring
  namespace: ml-workshop
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - services
      - endpoints
      - pods
  - verbs:
      - get
    apiGroups:
      - '*'
    resources:
      - configmaps
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - "*"
    verbs:
    - get
    - list 
    - watch      

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-monitoring-view
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  - statefulsets
  verbs:
  - get      


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-view
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: prometheus-operator-view
# rules:
# - apiGroups:
#   - monitoring.coreos.com
#   resources:
#   - "*"
#   verbs:
#   - get
#   - list 
#   - watch
# - apiGroups:
#   - "*"
#   resources:
#   - secrets
#   - statefulsets
#   - configmaps
#   - namespaces
#   - pods
#   - services
#   - nodes
#   - endpoints
#   - nodes/metrics
#   verbs:
#   - get
#   - list 
#   - watch  
# - apiGroups:
#   - "networking.k8s.io"
#   resources:
#   - ingresses
#   verbs:
#   - get
#   - list 
#   - watch    