apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - secrets.yaml
  - service.yaml
  - service-accounts.yaml
  - ingress.yaml
  - default-role-binding.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "airflow2"



configMapGenerator:
- name: airflowparameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: KEYCLOAK_URL
  objref:
    kind: ConfigMap
    name: airflowparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.KEYCLOAK_URL
- name: CLIENT_SECRET
  objref:
    kind: ConfigMap
    name: airflowparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.CLIENT_SECRET
- name: AIRFLOW_HOST
  objref:
    kind: ConfigMap
    name: airflowparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.AIRFLOW_HOST
- name: DAG_REPO
  objref:
    kind: ConfigMap
    name: airflowparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.DAG_REPO
