---
# Source: airflow/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-aflow-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.9.4
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm
  namespace: ml-workshop
type: Opaque
data:
  postgresql-postgres-password: "UTBVTmdlRlZ4Rw=="
  postgresql-password: "TXpnTUdJVXJ4bg=="

---
# Source: airflow/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-aflow-redis
  namespace: "ml-workshop"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.8.11
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "T2lCdE1VUkIxcA=="
---
# Source: airflow/templates/config/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-aflow-airflow
  labels:
    app.kubernetes.io/name: airflow
    helm.sh/chart: airflow-10.3.2
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  airflow-password: "a3VYaW1tbXhDVw=="

  airflow-fernetKey: "VEdKeGRXMXhUVU5KTWpCclVuUXlRblF5VVhOUlFUSjFjbEp6TWpoWVJVMD0="