---
# Source: airflow/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: app-aflow-redis
  namespace: "ml-workshop"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.8.11
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: airflow2
  name: airflow2-core


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow2-proxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ap-airflow2"}}'

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow2-proxy
  annotations:
    kubernetes.io/service-account.name: airflow2-proxy
type: kubernetes.io/service-account-token
