apiVersion: v1
kind: Service
metadata:
  name: flightsdatadb
  labels:
    app: flightsdatadb
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: flightsdatadb