apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-ingress.yaml
  - minio-configmap.yaml
  - minio-pvc.yaml
  - minio-dc.yaml
  - minio-service.yaml
  - minio-job.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "minio"


configMapGenerator:
- name: minioparameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: MINIO_HOST
  objref:
    kind: ConfigMap
    name: minioparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.MINIO_HOST
