apiVersion: v1
kind: Service
metadata:
  name: pg-flights-data
  labels:
    app: pg-flights-data
spec:
  ports:
   - port: 5432
     protocol: TCP
     targetPort: 5432
  selector:
   app: pg-flights-data