apiVersion: v1
kind: Service
metadata:
  name: fastapi-streamlit-service
spec:
  selector:
    app: fastapi-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501 # Streamlit's default port
  type: LoadBalancer
