version: "3"

services:
  prep:
    container_name: prep
    image: shibui/ml-system-in-actions:prep_pred_pattern_prep_0.0.1
    restart: always
    environment:
      - PLATFORM=docker_compose
      - API_ADDRESS=pred
    ports:
      - "8000:8000"
    command: ./run.sh
    depends_on:
      - pred

  pred:
    container_name: pred
    image: shibui/ml-system-in-actions:prep_pred_pattern_pred_0.0.1
    restart: always
    environment:
      - HTTP_PORT=8001
      - GRPC_PORT=50051
    ports:
      - "8001:8001"
      - "50051:50051"
    entrypoint: ["./onnx_runtime_server_entrypoint.sh"]
