apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - image-stream-crd.yaml
  # - route-crd.yaml
  - operatorgroup.yaml
  - limits.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odh-common

configMapGenerator:
- name: commonparameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: commonparameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
