service: basic-todo-resources
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin

# you can define service wide environment variables here
environment:
  AWS_ACCOUNT_ID: my_AWS_account_ID
  BASIC_TODO_DATA_BUCKET: myBucketName


custom:
  dataBucket: ${env:BASIC_TODO_DATA_BUCKET}
  region: ${env:AWS_DEFAULT_REGION, 'ap-northeast-2'}
  accountid: ${env:AWS_ACCOUNT_ID}
  dotenv:
    path: ../.env


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'ap-northeast-2'}


resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.dataBucket}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - 
                  GET
                  PUT
                  POST
                  DELETE
                  HEAD
              MaxAge: 3000
        AccessControl: PublicRead
    DataBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: DataBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.dataBucket}/*
