version: "3"

services:
  sample:
    container_name: sample
    image: shibui/ml-system-in-actions:sample_0.0.1
    restart: always
    environment:
      - PLATFORM=docker_compose
    ports:
      - "8000:8000"
    command: ./run.sh
