apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkhistoryservers.radanalytics.io
spec:
  conversion:
    strategy: None
  group: radanalytics.io
  names:
    kind: SparkHistoryServer
    listKind: SparkHistoryServerList
    plural: sparkhistoryservers
    singular: sparkhistoryserver
  # preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
     openAPIV3Schema:
      description: >-
        Defining the CRD so to use the as-is jhhub from ODH
      type: object
      properties:
        spec:
          type: object
          x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}          