apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radanalytics-spark-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radanalytics-spark-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          value: ml-workshop
        - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
          value: ml-workshop  
        - name: INGRESS_HOST
          value: $(INGRESS_HOST)  
        image: quay.io/ml-on-k8s/spark-operator:1.3.3
        imagePullPolicy: Always
        name: spark-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      imagePullPolicy: Always
      securityContext: {}
      serviceAccount: spark-operator
      serviceAccountName: spark-operator
      terminationGracePeriodSeconds: 5
